version: "3.9"

services:
    api:
        build:
            context: .
            dockerfile: ./docker/local/django/Dockerfile
        command: /start
        volumes:
            - .:/app:z
            - static_volume:/app/staticfiles
            - media_volume:/app/mediafiles
        expose:
            - "8000"
        ports:
            - "8000:8000"  # Django
            - "8890:8890"  # Jupyter
        env_file:
            - ./.envs/.local/.django
            - ./.envs/.local/.postgres
        depends_on:
            - postgres
            - mailhog
            - redis
        networks:
            - {{ cookiecutter.project_name }}

    client:
        build:
            context: .
            dockerfile: ./client/docker/local/Dockerfile
        restart: on-failure
        volumes:
            - ./client:/app
            - /app/node_modules
        networks:
            - {{ cookiecutter.project_name }}

    postgres:
        build:
            context: .
            dockerfile: ./docker/local/postgres/Dockerfile
        volumes:
            - local_postgres_data:/var/lib/postgresql/data
            - local_postgres_data_backups:/backups
        ports:
            - "5432:5432"
        env_file:
            - ./.envs/.local/.postgres
        networks:
            - {{ cookiecutter.project_name }}

    mailhog:
        image: mailhog/mailhog:v1.0.0
        container_name: mailhog
        ports:
            - "8025:8025"
        networks:
            - {{ cookiecutter.project_name }}
    
    redis:
        image: redis:7-alpine
        container_name: redis
        networks:
            - {{ cookiecutter.project_name }}

    celery_worker:
        build:
            context: .
            dockerfile: ./docker/local/django/Dockerfile
        command: /start-celeryworker
        volumes:
            - .:/app
        env_file:
            - ./.envs/.local/.django
            - ./.envs/.local/.postgres
        depends_on:
            - mailhog
            - redis
            - postgres
        networks:
            - {{ cookiecutter.project_name }}
            
    flower:
        build:
            context: .
            dockerfile: ./docker/local/django/Dockerfile
        command: /start-flower
        volumes:
            - flower_data:/data
        env_file:
            - ./.envs/.local/.django
            - ./.envs/.local/.postgres
        depends_on:
            - redis
            - postgres
        ports:
            - "5555:5555"
        networks:
            - {{ cookiecutter.project_name }}

    nginx:
        build:
            context: .
            dockerfile: ./docker/local/nginx/Dockerfile
        restart: always
        volumes:
            - static_volume:/app/staticfiles
            - media_volume:/app/mediafiles
        ports:
            - "1337:80"
        depends_on:
            - api
        networks:
            - {{ cookiecutter.project_name }}

networks:
    {{ cookiecutter.project_name }}:
        driver: bridge

volumes:
    static_volume:
    media_volume:
    local_postgres_data: {}
    local_postgres_data_backups: {}
    flower_data: {}
    django-jupyter-notebooks: {}
