#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# Run Django migrations
echo "Applying migrations..."
python manage.py makemigrations users
python manage.py makemigrations profiles

# Apply migrations
python manage.py migrate

# Collect static files
echo "Collecting static files..."
python manage.py collectstatic --no-input

# Start Django server in the background
echo "Starting Django server..."
python manage.py runserver 0.0.0.0:8000 &

# Start Jupyter Lab in the foreground
echo "Starting Jupyter Lab..."
exec jupyter lab --ip=0.0.0.0 --port=8890 --no-browser --allow-root --config=/root/.jupyter/jupyter_server_config.py
